### ISSUE TITLE
Transparent background / overlay possibility ?

### ISSUE THREAD

**Issue by ocZio** [ajstarks/openvg#11]
Hi,

I am trying to create a simple text overlay on top of an existing opengl running application, is this possible ? 

I tried to create a BackgroundRGB(0, 0, 0, 0.1); but even with this it seems to cover the whole screen with a black background. When I remove the background I have a yellow background. 

Any hints? :-)

My program is:
```cpp
int main() {
	int width, height;
	char s[3];
	
	init(&width, &height);                  // Graphics initialization
	
	VGfloat color[4] = { 255, 255, 255, 1 };
	vgSetfv(VG_CLEAR_COLOR, 4, color);
	vgClear(0, 0, 100, 200);
	color[0] = 0, color[1] = 0, color[2] = 0;
	setfill(color);
	setstroke(color);
	StrokeWidth(0);
	vgLoadIdentity();
	
	Fill(255, 255, 255, 1);                 // White text
	TextMid(width / 2, height / 2, "hello, world", SerifTypeface, width / 10);  // Greetings
	End();                                  // End the picture
	
	fgets(s, 2, stdin);                     // look at the pic, end with [RETURN]
	finish();                               // Graphics cleanup
	exit(0);
}
```

**Comment by ajstarks** [comment]
See revision d0e60d3

**Comment by LucaSoldi** [comment]
HI! I have changed the alpha value in libshape.c, but background alpha not changed :) Can you post an example of a working code? :) thanks!

**Comment by paeryn** [comment]
In the update with my window handling code there has been a change in how the hardware alpha blends the window when displaying it. Previously it blended each pixel of the window with the alpha value of that pixel whereas now a single alpha value is used for the whole window and the individual per-pixel alpha values aren't used for display (OpenVG still uses them for drawing). To regain the old method you need to change line 84 in oglinit.c : change the current
```
	static VC_DISPMANX_ALPHA_T alpha = {
		DISPMANX_FLAGS_ALPHA_FIXED_ALL_PIXELS,
		255, 0
	};
```
to
```
	static VC_DISPMANX_ALPHA_T alpha = {
		DISPMANX_FLAGS_ALPHA_FROM_SOURCE,
		255, 0
	};
```

**Comment by LucaSoldi** [comment]
Thanks man!! You save my day 👍
