### ISSUE TITLE
Is GO required?

### ISSUE THREAD

**Issue by AndrewMascolo** [ajstarks/openvg#23]
Im using Geany to make and edit my programs but every time I compile one of the sample porgrams, I get an error about "VG/openvg.h" saying it can't find it. 

I looked through the files myself and I can't even find the openvg.h either. 

PS. I am on my Raspberry Pi on whatever the most recent Raspian version is.

**Comment by ajstarks** [comment]
Go is not required.  You can write programs in C or Go.
Are you using the Makefile to build? If not, you need to specify the Include path 
-I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads
