### ISSUE TITLE
openvg fails to load in raspberry's 2 models

### ISSUE THREAD

**Issue by ottoecheverri** [ajstarks/openvg#25]
after downloading from the github, the make fails with an error.
programs that had been created in the model 1 like "shapedemo" give an error as:
"oglinit.c oglinit:Assertion 'state->surface !=CCEGLSurface(0)' failed"

**Comment by ajstarks** [comment]
things to check:

1) the amount of RAM allotted to the GPU (see /boot/config.txt)
2) What language are you using, C or Go?
3) Do you have any other process doing graphics?

**Comment by ottoecheverri** [comment]
Sorry, I was not following ALL the instructions and was missing the apt-get install at the beginning. Everything is working fine. Thanks for your help. (I am using C)
