### ISSUE TITLE
install on OSX issue

### ISSUE THREAD

**Issue by joeblew99** [ajstarks/openvg#26]
go get -u github.com/ajstarks/openvg
# github.com/ajstarks/openvg
openvg/openvg.go:7:10: fatal error: 'VG/openvg.h' file not found
#include "VG/openvg.h"
         ^
1 error generated.

**Comment by ajstarks** [comment]
Currently only works on the Raspberry Pi (which has the appropriate headers)

**Comment by joeblew99** [comment]
Ok. Please close
