### ISSUE TITLE
Build fails on archlinux (armv7) without -fPIC

### ISSUE THREAD

**Issue by jholster** [ajstarks/openvg#37]
Building openvg on archlinux (armv7 / rpi2) fails:

$ make
/usr/bin/ld: libshapes.o: relocation R_ARM_MOVW_ABS_NC against `stdin' can not be used when making a shared object; recompile with -fPIC

To fix the issue, you have add -fPIC to INCLUDEFLAGS:

diff --git a/Makefile b/Makefile
index 3976e3e..e454b92 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
-INCLUDEFLAGS=-I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads
+INCLUDEFLAGS=-I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -fPIC
 LIBFLAGS=-L/opt/vc/lib -lGLESv2 -lEGL -ljpeg
-FONTLIB=/usr/share/fonts/truetype/ttf-dejavu
+FONTLIB=/usr/share/fonts/TTF
 FONTFILES=DejaVuSans.inc  DejaVuSansMono.inc DejaVuSerif.inc
 all:   font2openvg fonts library

**Comment by ajstarks** [comment]
fixed
