### ISSUE TITLE
Slight error in a colour definition

### ISSUE THREAD

**Issue by paeryn** [ajstarks/openvg#40]
On line 582 of libshapes.c, right as the start of Start() you set the colour value to {255, 255, 255, 1} whereas it should be {1, 1, 1, 1} - all colour values are in the range [0-1], it works due to anything over 1.0 being clamped to 1.0.

void Start(int width, int height) {
	VGfloat color[4] = { 255, 255, 255, 1 };    // Should be {1, 1, 1, 1};

**Comment by ajstarks** [comment]
fixed.
