### ISSUE TITLE
add existing func to shapes.h: VGImage createImageFromJpeg(const char *filename)

### ISSUE THREAD

**Issue by steverpi** [ajstarks/openvg#46]
I am writing a new mouse routine and need to copy a jpg file (small thumbnail pictures) into VGImage mem bufs which can be later moved and placed on the screen.  I see that libshapes.c has this function, which looks as though it could do this.

VGImage createImageFromJpeg(const char *filename)

Is is possible to add this existing within shapes.h to allow accessing it.

---
Also, does anyone know how to save an area of the screen as a jpeg file, which would allow screen shots to be saved.

Thanks
Steve

**Comment by ajstarks** [comment]
fixed with revision e8f4b6d
