### ISSUE TITLE
const char *

### ISSUE THREAD

**Issue by steverpi** [ajstarks/openvg#49]
Sincere thanks for the update change from char * to const char *.  For completeness, could the remaining 2 funcs still using char * also be changed to const char *, which are:

extern void Image(VGfloat, VGfloat, int, int, char *);

extern void SaveEnd(char *); 

Thanks again as the change has saved MB of space and cleared up all of the distracting warnings!

**Comment by ajstarks** [comment]
fixed with revision  1fb18a7
