### ISSUE TITLE
[Suggestion] Changing CGO flags on Raspbian Stretch

### ISSUE THREAD

**Issue by Preston-PLB** [ajstarks/openvg#67]
In order to use the go library in Raspbian Stretch, you must change `line 6` of `openvg.go`
`#cgo LDFLAGS:  -L/opt/vc/lib -lGLESv2 -lEGL -lbcm_host -ljpeg`
to
`#cgo LDFLAGS:  -L/opt/vc/lib -lbrcmGLESv2 -lbrcmEGL -lbcm_host -ljpeg`

just like in the makefile from [Issue#62](https://github.com/ajstarks/openvg/issues/62)

I don't know if something should be noted in the README.md or have a commented line in each file that a stretch user can uncomment so all goes smoothly.

Keep up the great work guys

**Comment by ajstarks** [comment]
Done with revision https://github.com/ajstarks/openvg/commit/5980ac1f81e50d7506ecb3f9b6a86504ba21f51b
