### ISSUE TITLE
Inconsistency on Circle/CircleOutline third parameter

### ISSUE THREAD

**Issue by sofianebaltaci** [ajstarks/openvg#70]
The documentation says :

`void Circle(VGfloat x, VGfloat y, VGfloat r)`
`Draw a circle centered at (x,y) with radius r.`

`Circle()` is just a wrapper around `Ellipse()` that directly pass `r` parameter, thus the advertised **`r` (radius) for `Circle()` must not be used as a radius but as a diameter at the current state of the codebase**.
see : https://github.com/ajstarks/openvg/blob/2b32039b3a540bb41f3d88460342700e2e04b5a7/libshapes.c#L608-L619

Please adapt the documentation to reflect this behaviour or adapt the code.

Thank you

**Comment by ajstarks** [comment]
fixed.
